name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  repository-to-clone:
    description: 'repo'
    required: true
  tag-to-checkout:
    description: 'tag'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - uses: actions/checkout@v3
      with:
#         repository: ${{ inputs.repository-to-clone }}
#         ref: ${{ inputs.tag-to-checkout }}
        path: ./curr-repo
        submodules: 'recursive'
    - run: tar -czvf source_code_with_modules.tar.gz ./curr-repo
      shell: bash
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: source_code_with_modules.tar.gz
      
